const tryList = [
  {
    word: "ability",
    translations: [{ translation: "能力，能耐；才能", type: "n" }],
    phrases: [
      { phrase: "innovation ability", translation: "创新能力" },
      { phrase: "ability for", translation: "在…的能力" },
      { phrase: "learning ability", translation: "学习能力" },
      { phrase: "practical ability", translation: "实践能力；实际能力" },
      { phrase: "technical ability", translation: "技术能力" },
      { phrase: "reading ability", translation: "阅读能力" },
      { phrase: "management ability", translation: "管理能力" },
      { phrase: "writing ability", translation: "写作能力；书写能力" },
      { phrase: "working ability", translation: "工作能力，加工能力" },
      { phrase: "physical ability", translation: "体能，体质能力；身体能力" },
      { phrase: "cognitive ability", translation: "认知能力" },
      { phrase: "service ability", translation: "工作能力" },
      { phrase: "ability to pay", translation: "支付能力" },
      { phrase: "combining ability", translation: "配合力" },
      { phrase: "develop ability", translation: "发挥才能" },
      { phrase: "executive ability", translation: "执行力；行政能力" },
      { phrase: "natural ability", translation: "本能" },
      { phrase: "administrative ability", translation: "行政能力；经营才能" },
      { phrase: "unique ability", translation: "独有能力" },
      { phrase: "adaptive ability", translation: "自适应能力" },
    ],
  },
  {
    word: "able",
    translations: [
      { translation: "能；[经管] 有能力的；能干的", type: "adj" },
      { translation: "(Able)人名；(伊朗)阿布勒；(英)埃布尔", type: "n" },
    ],
    phrases: [
      { phrase: "will be able to", translation: "将能够" },
      { phrase: "be able to do", translation: "能够做" },
      {
        phrase: "be able to take",
        translation: "经受得住某事(指困难、痛苦的事)",
      },
      { phrase: "able person", translation: "能人；有能力的人；有用的人才" },
      { phrase: "spell able", translation: "干练的；有能力的" },
      {
        phrase: "able seaman",
        translation: "一级水手；熟练水手；[英国，加拿大]二等水兵",
      },
    ],
  },
  {
    word: "about",
    translations: [
      { translation: "关于；大约", type: "prep" },
      { translation: "在附近的；四处走动的；在起作用的", type: "adj" },
      { translation: "大约；周围；到处", type: "adv" },
      { translation: "大致；粗枝大叶；不拘小节的人", type: "n" },
    ],
    phrases: [
      { phrase: "how about", translation: "你认为…怎样" },
      { phrase: "what about", translation: "怎么样；（对于）…怎么样" },
      { phrase: "all about", translation: "到处，各处；关于…的一切" },
      { phrase: "about us", translation: "关于我们；公司简介" },
      { phrase: "do about", translation: "处理；应付；就某事采取行动或措施" },
      { phrase: "go about", translation: "v. 着手做；四处走动；传开；从事" },
      { phrase: "about to do", translation: "刚要；即将" },
      { phrase: "about of", translation: "打算；即将" },
      { phrase: "out and about", translation: "能够外出走动" },
      { phrase: "up and about", translation: "（病人病情好转）起床走动" },
      { phrase: "on or about", translation: "大约于…" },
    ],
  },
  {
    word: "above",
    translations: [
      { translation: "超过；在……上面；在……之上", type: "prep" },
      { translation: "在上面；在上文", type: "adv" },
      { translation: "上文的", type: "adj" },
      { translation: "上文", type: "n" },
    ],
    phrases: [
      { phrase: "above oneself", translation: "自高自大；趾高气扬；兴高采烈" },
      { phrase: "above all", translation: "首先；尤其是" },
      { phrase: "from above", translation: "从…上面；从上级；从天上" },
      { phrase: "all above", translation: "以上都是；所有上面的" },
      { phrase: "all of the above", translation: "上述全部" },
      { phrase: "well above", translation: "大大超过；远高于…" },
      { phrase: "over and above", translation: "除…之外；在…之上" },
      { phrase: "above and beyond", translation: "大于" },
      { phrase: "get above oneself", translation: "变得自高自大；自视甚高" },
    ],
  },
  {
    word: "abroad",
    translations: [
      { translation: "在国外；到海外", type: "adv" },
      { translation: "往国外的", type: "adj" },
      { translation: "海外；异国", type: "n" },
    ],
    phrases: [
      { phrase: "home and abroad", translation: "国内外，海内外" },
      { phrase: "at home and abroad", translation: "国内外" },
      { phrase: "study abroad", translation: "出国留学；海外学习" },
      { phrase: "go abroad", translation: "去国外，出国" },
      { phrase: "studying abroad", translation: "出国留学；出国学习" },
      { phrase: "went abroad", translation: "出国" },
      { phrase: "travel abroad", translation: "vi. 出国旅行" },
      { phrase: "spread abroad", translation: "传播" },
      { phrase: "market abroad", translation: "海外市场" },
      { phrase: "student abroad", translation: "n. 留学生" },
      { phrase: "consumption abroad", translation: "境外消费（服务贸易）" },
    ],
  },
  {
    word: "absent",
    translations: [
      { translation: "缺席的；缺少的；心不在焉的；茫然的", type: "adj" },
      { translation: "使缺席", type: "v" },
    ],
    phrases: [
      { phrase: "absent from", translation: "缺席" },
      { phrase: "absent minded", translation: "健忘的" },
      { phrase: "absent from work", translation: "旷工；缺勤" },
    ],
  },
  {
    word: "accent",
    translations: [
      { translation: "口音；重音；强调；特点；重音符号", type: "n" },
      { translation: "强调；重读；带…口音讲话", type: "v" },
    ],
  },
  {
    word: "accept",
    translations: [{ translation: "接受；承认；承担；承兑；容纳", type: "v" }],
    phrases: [{ phrase: "accept of", translation: "v. 承兑" }],
  },
  {
    word: "accident",
    translations: [
      { translation: "事故；意外；[法] 意外事件；机遇", type: "n" },
    ],
    phrases: [
      { phrase: "traffic accident", translation: "交通事故" },
      { phrase: "by accident", translation: "偶然；意外地" },
      { phrase: "car accident", translation: "车祸；交通事故" },
      { phrase: "accident insurance", translation: "意外保险；事故保险" },
      { phrase: "accident prevention", translation: "事故预防；安全措施" },
      { phrase: "fire accident", translation: "火灾事故；失火" },
      { phrase: "accident rate", translation: "意外伤害率" },
      { phrase: "road accident", translation: "交通事故" },
      { phrase: "fatal accident", translation: "死亡事故" },
      { phrase: "nuclear accident", translation: "核事故" },
      {
        phrase: "industrial accident",
        translation: "工伤事故；工业事故；劳动事故",
      },
      { phrase: "have an accident", translation: "vi. 出事故" },
      {
        phrase: "cerebrovascular accident",
        translation: "[医]脑血管意外（等于中风）；脑血管伤害",
      },
      {
        phrase: "personal accident insurance",
        translation: "个人人身意外伤害保险",
      },
      { phrase: "collision accident", translation: "碰撞事故；空中相撞事故" },
      { phrase: "vehicle accident", translation: "交通事故" },
      {
        phrase: "aviation accident",
        translation: "航空事故；飞机失事；飞行事故",
      },
      { phrase: "transportation accident", translation: "交通事故" },
      { phrase: "minor accident", translation: "轻微事故；小事故" },
      { phrase: "unexpected accident", translation: "不能预料的事故" },
    ],
  },
  {
    word: "ache",
    translations: [
      { translation: "疼痛；渴望", type: "v" },
      { translation: "疼痛", type: "n" },
    ],
    phrases: [
      { phrase: "aches and pains", translation: "痛苦；不适；各种各样的病痛" },
      { phrase: "stomach ache", translation: "胃疼" },
      { phrase: "ache for", translation: "想念，渴望" },
      { phrase: "tooth ache", translation: "牙痛" },
      { phrase: "ache all over", translation: "全身疼痛" },
    ],
  },
  {
    word: "achieve",
    translations: [{ translation: "取得；获得；实现；成功", type: "v" }],
    phrases: [
      { phrase: "achieve success", translation: "取得成功；获得成功" },
      { phrase: "achieve one's goals", translation: "实现目标" },
    ],
  },
  {
    word: "across",
    translations: [
      { translation: "穿过；横穿", type: "prep" },
      { translation: "横过；在对面", type: "adv" },
    ],
    phrases: [
      {
        phrase: "across the board",
        translation: "全面地；包括一切地；以三等分的钱数赌同一匹马赢得前三名",
      },
      { phrase: "across from", translation: "在…对面" },
      { phrase: "go across", translation: "穿过，横过；走过" },
      { phrase: "back across", translation: "后背宽" },
    ],
  },
  {
    word: "act",
    translations: [
      { translation: "扮演；装作，举动像", type: "v" },
      {
        translation:
          "行为，行动；法令，法案；（戏剧，歌剧的）一幕，段；装腔作势",
        type: "n",
      },
    ],
    phrases: [
      { phrase: "act as", translation: "担当" },
      { phrase: "act on", translation: "对…起作用；按照…行事" },
      { phrase: "act in", translation: "扮演；在…方面行动" },
      { phrase: "act like", translation: "举止像..." },
      { phrase: "act for", translation: "v. 代理" },
      { phrase: "in act", translation: "[古语]即将，正要(与to和不定式连用)" },
      { phrase: "speech act", translation: "言语行为" },
      { phrase: "act out", translation: "把…表演出来；把…付诸行动" },
      { phrase: "act with", translation: "以…方式行事" },
      { phrase: "act upon", translation: "对…起作用；按照…行事" },
      { phrase: "act against", translation: "vt. 违反" },
      { phrase: "in the act of", translation: "正在做…时" },
      { phrase: "legal act", translation: "法律行为" },
      { phrase: "education act", translation: "教育法" },
      { phrase: "juristic act", translation: "法律行为；法律行律" },
      { phrase: "criminal act", translation: "罪行，犯罪行为" },
      { phrase: "act of god", translation: "天灾；不可抗力" },
      { phrase: "act accordingly", translation: "核办" },
      { phrase: "balancing act", translation: "平衡做法；协调" },
      { phrase: "illegal act", translation: "不法行为，非法行为" },
    ],
  },
  {
    word: "action",
    translations: [{ translation: "行动；活动；功能；战斗；情节", type: "n" }],
    phrases: [
      { phrase: "take action", translation: "采取行动；提出诉讼" },
      { phrase: "action on", translation: "对…的作用" },
      { phrase: "in action", translation: "在活动；在运转" },
      { phrase: "action plan", translation: "行动计划；行动方案" },
      { phrase: "mechanism of action", translation: "作用机制；作用机理" },
      { phrase: "course of action", translation: "做法；行动步骤" },
      { phrase: "legal action", translation: "法律诉讼" },
      {
        phrase: "action research",
        translation: "行动研究；行为研究；动作研究",
      },
      { phrase: "civil action", translation: "n. 民事诉讼" },
      { phrase: "pharmacological action", translation: "药理作用" },
      { phrase: "corrective action", translation: "n. 校正动作" },
      { phrase: "administrative action", translation: "行政诉讼；行政裁定" },
      {
        phrase: "joint action",
        translation: "联合行动；[机]接合动作；接合作用",
      },
      { phrase: "collective action", translation: "集体行动；集体行为" },
      {
        phrase: "combined action",
        translation: "共同作用；联合行动；复合作用",
      },
      { phrase: "direct action", translation: "直接行动；直接作用" },
      { phrase: "action potential", translation: "动作电位；动诅位" },
      { phrase: "out of action", translation: "损坏；不运转；失去作用" },
      { phrase: "control action", translation: "控制作用；控制动作" },
      { phrase: "disciplinary action", translation: "纪律处分；训练活动" },
    ],
  },
  {
    word: "active",
    translations: [
      { translation: "积极的；活跃的；主动的；有效的；现役的", type: "adj" },
      { translation: "主动语态；积极分子", type: "n" },
    ],
    phrases: [
      { phrase: "active in", translation: "积极于" },
      { phrase: "active role", translation: "积极任务；活跃角色" },
      { phrase: "active part", translation: "积极的作用；能动部分，主动部分" },
      { phrase: "active power", translation: "有功（有效）功率" },
      { phrase: "active carbon", translation: "活性炭；活性炭黑" },
      { phrase: "surface active", translation: "表面活性的" },
      { phrase: "active ingredient", translation: "有效成分；活性组分" },
      { phrase: "active participation", translation: "主动参与；积极参加" },
      { phrase: "active agent", translation: "活性剂" },
      {
        phrase: "active component",
        translation: "活性组分；有效元件；作用分量",
      },
      { phrase: "surface active agent", translation: "表面活性剂" },
      { phrase: "active service", translation: "现役" },
      { phrase: "active oxygen", translation: "活性氧" },
      { phrase: "active fault", translation: "活动断裂；活性断层" },
      { phrase: "active learning", translation: "主动学习；积极学习" },
      {
        phrase: "active substance",
        translation: "活性物质；放射性物质；有效物质",
      },
      {
        phrase: "active suspension",
        translation: "主动制导悬架系统（一种由计算机控制的机动车悬架系统）",
      },
      { phrase: "active material", translation: "[核物]活性物质，放射性材料" },
      { phrase: "active network", translation: "有源网络" },
      { phrase: "active member", translation: "积极成员；活跃会员" },
    ],
  },
  {
    word: "activity",
    translations: [{ translation: "活动；行动；活跃", type: "n" }],
    phrases: [
      { phrase: "economic activity", translation: "经济活动" },
      { phrase: "catalytic activity", translation: "催化活性" },
      {
        phrase: "physical activity",
        translation: "身体活动，体育活动；体力活动",
      },
      { phrase: "biological activity", translation: "生物活性" },
      { phrase: "enzyme activity", translation: "酶活力" },
      {
        phrase: "business activity",
        translation: "商业活动，经济活动；业务活动",
      },
      { phrase: "social activity", translation: "社会行动" },
      { phrase: "brain activity", translation: "大脑活动" },
      { phrase: "sexual activity", translation: "性活动；性行为" },
      { phrase: "seismic activity", translation: "地震活动；地震活动性" },
      {
        phrase: "antimicrobial activity",
        translation: "抗菌活性；抗菌能力；抗微生物活性",
      },
      { phrase: "volcanic activity", translation: "火山活动；火山活动性" },
      { phrase: "electrical activity", translation: "电活动，脑电活动" },
      { phrase: "enzymatic activity", translation: "酶活性；酶活力" },
      { phrase: "practical activity", translation: "实践活动" },
      { phrase: "solar activity", translation: "太阳活动；太阳活动性" },
      { phrase: "water activity", translation: "水分活度；水分活性" },
      { phrase: "marketing activity", translation: "销售活动" },
      { phrase: "outdoor activity", translation: "户外活动，室外活动" },
      { phrase: "activity level", translation: "活动级；活动程度" },
    ],
  },
  {
    word: "add",
    translations: [
      { translation: "加；增加；加起来；做加法", type: "v" },
      { translation: "加法，加法运算", type: "n" },
    ],
    phrases: [
      { phrase: "add up", translation: "v. 合计" },
      { phrase: "add in", translation: "添加；把…包括在内" },
      { phrase: "add value", translation: "增加价值；附加价值；添加值" },
      { phrase: "add on", translation: "插入；另外加上去" },
      { phrase: "add noise", translation: "添加杂色；添加噪声" },
      {
        phrase: "add weight to",
        translation: "进一步证明；扩大影响；增强优势；加重",
      },
    ],
  },
  {
    word: "address",
    translations: [
      {
        translation:
          "演说；从事；忙于；写姓名地址；向…致辞；与…说话；提出；处理",
        type: "v",
      },
      { translation: "地址；演讲；致辞；说话的技巧；称呼", type: "n" },
    ],
    phrases: [
      { phrase: "email address", translation: "电子邮箱信箱" },
      { phrase: "ip address", translation: "网络地址，IP地址" },
      { phrase: "address book", translation: "通讯簿；住址名册" },
      { phrase: "home address", translation: "家庭住址；标识地址；内部地址" },
      { phrase: "mailing address", translation: "邮寄地址" },
      { phrase: "network address", translation: "网络地址" },
      { phrase: "address space", translation: "地址空间" },
      { phrase: "address as", translation: "称呼" },
      { phrase: "e-mail address", translation: "电子邮件地址" },
      { phrase: "public address", translation: "公用地址；扩音装置" },
      { phrase: "address system", translation: "地址系统；称谓系统" },
      { phrase: "inaugural address", translation: "就职演说" },
      { phrase: "address translation", translation: "地址转换；位址翻译" },
      {
        phrase: "public address system",
        translation: "扩声系统；有线广播系统；公用地址系统",
      },
      { phrase: "correspondence address", translation: "通讯地址；通信地址" },
      { phrase: "specific address", translation: "专用地址" },
      { phrase: "full address", translation: "全地址" },
      { phrase: "physical address", translation: "物理地址；实际地址" },
      { phrase: "permanent address", translation: "永久地址；永久住址；原籍" },
      { phrase: "mail address", translation: "邮件地址；信件地址" },
    ],
  },
  {
    word: "advertisement",
    translations: [{ translation: "广告，宣传", type: "n" }],
    phrases: [
      { phrase: "advertisement company", translation: "广告公司" },
      { phrase: "commercial advertisement", translation: "商业广告" },
      { phrase: "advertisement plan", translation: "广告策划" },
      { phrase: "classified advertisement", translation: "分类广告" },
    ],
  },
  {
    word: "advice",
    translations: [{ translation: "建议；忠告；劝告；通知", type: "n" }],
    phrases: [
      { phrase: "seek advice", translation: "征求意见；请教" },
      { phrase: "good advice", translation: "好建议" },
      { phrase: "give advice", translation: "劝告，忠告" },
      { phrase: "legal advice", translation: "法律意见；[法]法律谘询" },
      { phrase: "expert advice", translation: "专家意见" },
      { phrase: "medical advice", translation: "医嘱；医务" },
      { phrase: "shipping advice", translation: "发货通知书" },
      { phrase: "take advice", translation: "请教；征求意见" },
      { phrase: "sound advice", translation: "忠告" },
      { phrase: "advice note", translation: "通知书，通知单" },
      { phrase: "take the advice", translation: "采纳建议；听从劝告" },
      {
        phrase: "advice of shipment",
        translation: "装船通知；装运通知；船运通知",
      },
      { phrase: "advice of credit", translation: "信用状通知书" },
    ],
  },
  {
    word: "advise",
    translations: [{ translation: "建议；劝告，忠告；通知；警告", type: "v" }],
    phrases: [
      { phrase: "please advise", translation: "请指导；请指示" },
      { phrase: "advise of", translation: "通知" },
    ],
  },
  {
    word: "afford",
    translations: [
      { translation: "给予，提供；买得起", type: "v" },
      { translation: "(Afford)人名；(英)阿福德", type: "n" },
    ],
    phrases: [{ phrase: "can afford", translation: "买得起；有能力负担" }],
  },
  {
    word: "afraid",
    translations: [{ translation: "害怕的；恐怕；担心的", type: "adj" }],
    phrases: [
      { phrase: "afraid of", translation: "害怕" },
      { phrase: "i'm afraid", translation: "我害怕；恐怕" },
    ],
  },
  {
    word: "after",
    translations: [
      { translation: "后来，以后", type: "adv" },
      { translation: "在……之后", type: "prep" },
      { translation: "在……之后", type: "conj" },
      { translation: "以后的", type: "adj" },
    ],
    phrases: [
      { phrase: "after all", translation: "毕竟；终究" },
      { phrase: "go after", translation: "追求，追逐" },
      { phrase: "ever after", translation: "从此以后一直" },
      { phrase: "after hours", translation: "adv. 下班；工作完毕后" },
    ],
  },
  {
    word: "afternoon",
    translations: [{ translation: "午后，下午", type: "n" }],
    phrases: [
      { phrase: "in the afternoon", translation: "adv. 在下午" },
      { phrase: "good afternoon", translation: "int. 下午好" },
      { phrase: "tomorrow afternoon", translation: "明天下午" },
      { phrase: "every afternoon", translation: "每天下午" },
      { phrase: "afternoon tea", translation: "下午茶" },
      { phrase: "on sunday afternoon", translation: "在星期天下午" },
      { phrase: "afternoon off", translation: "下午请假；下午放假" },
      { phrase: "lazy afternoon", translation: "闲散午后" },
      {
        phrase: "of an afternoon",
        translation: "[用于修饰经常性动作]往往(或常常)在下午",
      },
    ],
  },
  {
    word: "again",
    translations: [
      { translation: "又，此外；再一次；再说；增加", type: "adv" },
      { translation: "（英、保）阿盖恩", type: "n" },
    ],
    phrases: [
      { phrase: "again and again", translation: "adv. 再三地，反复地" },
      { phrase: "try again", translation: "再来一次" },
      { phrase: "over again", translation: "再一次" },
      { phrase: "come again", translation: "回来；重新赶上去；回去" },
      { phrase: "over and over again", translation: "adv. 一再地；反复不断地" },
      { phrase: "never again", translation: "拒绝再玩，不再；再也不会" },
      { phrase: "time and again", translation: "adv. 屡次；常常" },
      { phrase: "rise again", translation: "死而复生" },
      { phrase: "yet again", translation: "再一次" },
      { phrase: "on again", translation: "易变化的；不肯定的" },
      { phrase: "begin again", translation: "重新开始；重做" },
      {
        phrase: "time and time again",
        translation: "一次又一次；多次，不断地",
      },
      { phrase: "start all over again", translation: "从头再来" },
      { phrase: "but then again", translation: "但在那时；话说回来" },
      { phrase: "now and again", translation: "adv. 不时；时而" },
      { phrase: "breathe again", translation: "宽心；再次呼吸" },
      { phrase: "please say it again", translation: "请再说一遍" },
      { phrase: "start over again", translation: "从头开始" },
      { phrase: "every now and again", translation: "偶尔，有时" },
      { phrase: "give again", translation: "归还" },
    ],
  },
  {
    word: "against",
    translations: [
      { translation: "反对，违反；靠；倚；防备", type: "prep" },
      { translation: "不利的；对立的", type: "adj" },
    ],
    phrases: [
      { phrase: "up against", translation: "面临" },
      { phrase: "go against", translation: "不利于；违反；反对" },
      {
        phrase: "over against",
        translation: "在…对面；正对着；与…相反；与…形成对照",
      },
      { phrase: "as against", translation: "与…相对照；比…" },
      { phrase: "back against", translation: "背朝着" },
    ],
  },
  {
    word: "age",
    translations: [
      { translation: "年龄；时代；寿命，使用年限；阶段", type: "n" },
      { translation: "成熟；变老", type: "v" },
    ],
    phrases: [
      { phrase: "at the age of", translation: "在…岁" },
      { phrase: "of age", translation: "成年" },
      { phrase: "old age", translation: "老年；晚年" },
      { phrase: "at one's age", translation: "在…这个年龄(或岁数)" },
      { phrase: "information age", translation: "信息时代" },
      { phrase: "years of age", translation: "岁；年岁" },
      { phrase: "new age", translation: "n. 新时代；新世纪" },
      { phrase: "with age", translation: "随着年龄的增长；因年久" },
      { phrase: "for one's age", translation: "就其年龄而论" },
      { phrase: "age group", translation: "同年龄范围内的人" },
      { phrase: "middle age", translation: "中年；中世纪" },
      { phrase: "average age", translation: "平均年龄" },
      { phrase: "young age", translation: "年轻时代；童年" },
      { phrase: "golden age", translation: "黄金时代；鼎盛时期" },
      { phrase: "ice age", translation: "冰期；[地]冰河时代" },
      { phrase: "modern age", translation: "现代；当代" },
      { phrase: "stone age", translation: "石器时代" },
      { phrase: "digital age", translation: "数字时代；数字化时代" },
      { phrase: "age structure", translation: "年龄构成；年龄分布" },
      { phrase: "retirement age", translation: "退休年龄" },
    ],
  },
  {
    word: "ago",
    translations: [
      { translation: "以前，以往", type: "adv" },
      { translation: "以前的；过去的", type: "adj" },
      { translation: "(Ago)人名；(英、西、意、塞、瑞典)阿戈", type: "n" },
    ],
  },
  {
    word: "agree",
    translations: [{ translation: "同意，赞成；承认；约定，商定", type: "v" }],
    phrases: [
      { phrase: "agree with", translation: "同意，和…意见一致" },
      { phrase: "agree on", translation: "对…取得一致意见" },
      { phrase: "agree in", translation: "在…方面意见一致；在…相同" },
      {
        phrase: "agree about",
        translation: "对…有相同的看法；就…取得一致意见",
      },
      { phrase: "agree upon", translation: "对…取得一致意见" },
      { phrase: "agree to do sth", translation: "赞成做某事" },
      { phrase: "agree to do something", translation: "同意做某事" },
      {
        phrase: "agree to disagree",
        translation: "消除分歧，求同存异；同意各自保留不同意见",
      },
      { phrase: "agree up sth", translation: "在某一点上取得一致意见" },
    ],
  },
  {
    word: "agreement",
    translations: [{ translation: "协议；同意，一致", type: "n" }],
    phrases: [
      { phrase: "agreement with", translation: "同…达成协议" },
      { phrase: "agreement on", translation: "一致意见" },
      { phrase: "in agreement", translation: "一致；同意；意见一致" },
      { phrase: "in agreement with", translation: "同意；与…一致" },
      {
        phrase: "trade agreement",
        translation: "n. （国际）贸易协定；雇用合同；劳资协议",
      },
      {
        phrase: "reach an agreement",
        translation: "达成协议；取得一致意见，达成共识",
      },
      { phrase: "come to an agreement", translation: "v. 达成协议" },
      { phrase: "general agreement", translation: "总协定" },
      { phrase: "agency agreement", translation: "[经]代理协议；通汇契约" },
      { phrase: "by agreement", translation: "约好" },
      { phrase: "mutual agreement", translation: "双方协定" },
      { phrase: "written agreement", translation: "书面协定；成文契约" },
      { phrase: "arbitration agreement", translation: "仲裁协定" },
      { phrase: "service agreement", translation: "服务协议" },
      { phrase: "contract agreement", translation: "合同协议；承包合同" },
      { phrase: "license agreement", translation: "[经]许可证协议" },
      { phrase: "international agreement", translation: "国际协议；国际协定" },
      { phrase: "entire agreement", translation: "全部协议；完整合约" },
      { phrase: "loan agreement", translation: "贷款协议；借款合同" },
      { phrase: "bilateral agreement", translation: "双边协定" },
    ],
  },
  {
    word: "air",
    translations: [
      { translation: "空气，大气；天空；样子；曲调", type: "n" },
      { translation: "使通风，晾干；夸耀", type: "v" },
    ],
    phrases: [
      {
        phrase: "in the air",
        translation: "在空中；悬而未决；在流传中；不设防",
      },
      { phrase: "air conditioning", translation: "空调；空气调节" },
      { phrase: "air pollution", translation: "大气污染，空气污染" },
      { phrase: "by air", translation: "乘飞机；通过航空途径" },
      { phrase: "air ticket", translation: "机票" },
      { phrase: "fresh air", translation: "新鲜空气" },
      { phrase: "air force", translation: "空军" },
      { phrase: "air conditioner", translation: "n. 空调设备；空气调节机" },
      { phrase: "air flow", translation: "气流；空气流量；空气流向" },
      { phrase: "air temperature", translation: "气温，空气温度" },
      { phrase: "hot air", translation: "吹牛；大话" },
      { phrase: "air pressure", translation: "气压；风压" },
      { phrase: "air compressor", translation: "空气压缩机" },
      { phrase: "on the air", translation: "在广播，广播中" },
      { phrase: "compressed air", translation: "压缩空气" },
      { phrase: "air transport", translation: "航空运输" },
      { phrase: "air condition", translation: "空调，空气调节设备" },
      { phrase: "on air", translation: "（无线电）广播的；送风期" },
      { phrase: "air defense", translation: "n. 防空" },
      { phrase: "air traffic", translation: "空中交通，航空运输；飞航" },
    ],
  },
  {
    word: "airline",
    translations: [
      { translation: "航空公司；航线", type: "n" },
      { translation: "航线的", type: "adj" },
    ],
    phrases: [
      { phrase: "airline ticket", translation: "飞机票" },
      { phrase: "airline industry", translation: "航空公司；航线" },
      { phrase: "airline company", translation: "航空公司" },
      {
        phrase: "international airline",
        translation: "国际航线，国际航空公司",
      },
      { phrase: "airline pilot", translation: "航空公司飞行员" },
      { phrase: "major airline", translation: "干线航空公司" },
      {
        phrase: "united airline",
        translation: "联合航空公司（美国一家航空公司）",
      },
    ],
  },
  {
    word: "airplane",
    translations: [{ translation: "飞机", type: "n" }],
    phrases: [
      { phrase: "by airplane", translation: "搭飞机" },
      { phrase: "model airplane", translation: "航空模型" },
      { phrase: "fly an airplane", translation: "开飞机" },
    ],
  },
  {
    word: "airport",
    translations: [{ translation: "机场；航空站", type: "n" }],
    phrases: [
      { phrase: "international airport", translation: "国际机场" },
      { phrase: "airport bus", translation: "机场巴士；机场班车" },
      { phrase: "airport terminal", translation: "航站楼；机场候机楼" },
      { phrase: "heathrow airport", translation: "希思罗机场，位于英国伦敦" },
      { phrase: "beijing capital airport", translation: "北京首都机场" },
      { phrase: "destination airport", translation: "目的地机场；到达机场" },
      { phrase: "london airport", translation: "n. 伦敦机场" },
      { phrase: "kennedy airport", translation: "肯尼迪机场（美国纽约）" },
      { phrase: "airport tax", translation: "机场税（机场建设费）" },
      { phrase: "domestic airport", translation: "国内机场" },
      {
        phrase: "san francisco international airport",
        translation: "旧金山国际机场；三藩市国际机场",
      },
      { phrase: "airport construction fee", translation: "机场建设费" },
      { phrase: "airport facilities", translation: "飞机场设施" },
      {
        phrase: "airport of departure",
        translation: "始发站；始发站机场；启运机场",
      },
    ],
  },
  {
    word: "alive",
    translations: [{ translation: "活着的；活泼的；有生气的", type: "adj" }],
    phrases: [
      { phrase: "alive with", translation: "充满着；洋溢着" },
      { phrase: "come alive", translation: "活跃起来；看上去像真的" },
      { phrase: "stay alive", translation: "活着；仍然活着" },
      { phrase: "alive and well", translation: "盛行的；依然存在的" },
      { phrase: "keep alive", translation: "点火电极；保持生机；使……活着" },
      { phrase: "alive and kicking", translation: "活蹦乱跳的" },
      { phrase: "any man alive", translation: "任何人" },
      {
        phrase: "be kept alive",
        translation: "使继续有效，使继续存在(或进行)",
      },
      { phrase: "more dead than alive", translation: "精疲力尽；累得要死" },
      { phrase: "skinned alive", translation: "严厉申斥；以压倒优势击败" },
      { phrase: "look alive", translation: "快点；注意" },
    ],
  },
  {
    word: "all",
    translations: [
      { translation: "全部的", type: "adj" },
      { translation: "全然地；越发", type: "adv" },
      { translation: "全部", type: "n" },
      { translation: "全部", type: "pron" },
    ],
    phrases: [
      { phrase: "all the", translation: "◎惟一的，仅有的" },
      { phrase: "all of", translation: "adv. 不少于；实足" },
      { phrase: "in all", translation: "总共，合计" },
      { phrase: "and all", translation: "等等；的确；此外；连…一齐都" },
      { phrase: "all over", translation: "到处，遍及；浑身；全部结束" },
      { phrase: "all over oneself", translation: "◎非常高兴；非常满意" },
      { phrase: "at all", translation: "（否定句）根本；究竟" },
      { phrase: "after all", translation: "毕竟；终究" },
      { phrase: "above all", translation: "首先；尤其是" },
      { phrase: "all in", translation: "疲乏到极点" },
      { phrase: "first of all", translation: "adv. 首先" },
      { phrase: "all of us", translation: "我们所有人（情景喜剧）" },
      { phrase: "all about", translation: "到处，各处；关于…的一切" },
      { phrase: "all along", translation: "自始至终，一直" },
      { phrase: "all for", translation: "完全赞成；急于得到" },
      { phrase: "for all of", translation: "就…来说" },
      { phrase: "all in all", translation: "总而言之；头等重要的东西" },
      { phrase: "that's all", translation: "就这样；说完了" },
      { phrase: "all out", translation: "全力以赴" },
      { phrase: "over all", translation: "全面地；遍及" },
    ],
  },
  {
    word: "allow",
    translations: [{ translation: "允许；给予；认可", type: "v" }],
    phrases: [
      { phrase: "allow for", translation: "考虑到，虑及" },
      { phrase: "allow of", translation: "容许" },
    ],
  },
  {
    word: "almost",
    translations: [{ translation: "差不多，几乎", type: "adv" }],
    phrases: [{ phrase: "almost all", translation: "几乎处处" }],
  },
  {
    word: "alone",
    translations: [
      { translation: "独自的；单独的；孤独的", type: "adj" },
      { translation: "独自地；单独地", type: "adv" },
    ],
    phrases: [
      { phrase: "let alone", translation: "更不必说；听任；不打扰" },
      { phrase: "all alone", translation: "独立地，独自地" },
      { phrase: "stand alone", translation: "孤立；独一无二" },
      { phrase: "alone with", translation: "与…一起" },
      { phrase: "live alone", translation: "独自生活；一个人住；单独居住" },
      { phrase: "left alone", translation: "不干涉，不管；放开" },
      { phrase: "feel alone", translation: "感到孤单" },
      { phrase: "go it alone", translation: "单干；独自过活" },
      { phrase: "go alone", translation: "一个人去；独自去" },
      { phrase: "travel alone", translation: "单独一人旅游" },
      { phrase: "leave alone", translation: "不打扰；不干涉；不管；不理" },
      { phrase: "alone with her", translation: "与她在一起（电影名称）" },
    ],
  },
  {
    word: "along",
    translations: [
      { translation: "一起；向前；来到", type: "adv" },
      { translation: "沿着；顺着", type: "prep" },
    ],
    phrases: [
      {
        phrase: "along with",
        translation: "沿（顺）着；连同…一起；与…一道；随同…一起",
      },
      {
        phrase: "get along",
        translation: "（勉强）生活；进展；（使）前进；与…和睦相处",
      },
      { phrase: "all along", translation: "自始至终，一直" },
      { phrase: "go along", translation: "进行；支持；前进；赞同" },
      { phrase: "come along", translation: "v. 出现；一起来；陪伴；进步" },
      { phrase: "go along with", translation: "赞同；陪…一起去" },
      { phrase: "along on", translation: "见all along of [见all]" },
      { phrase: "right along", translation: "继续地" },
      {
        phrase: "along for the ride",
        translation: "沽名钓誉的；(在团体中)图虚名而不做工作的；逢场作戏；陪伴",
      },
      { phrase: "along there", translation: "在那个方向，朝那个方向" },
      { phrase: "along here", translation: "在这个方向，朝这个方向" },
      { phrase: "along of", translation: "见all along of [见all]" },
    ],
  },
  {
    word: "aloud",
    translations: [{ translation: "大声地；出声地", type: "adv" }],
    phrases: [
      { phrase: "read aloud", translation: "大声朗读" },
      { phrase: "reading aloud", translation: "大声朗读；大声朗诵" },
      { phrase: "thinking aloud", translation: "[心理学]出声思维；放声思考" },
      { phrase: "think aloud", translation: "边想边说出，自言自语" },
    ],
  },
  {
    word: "already",
    translations: [{ translation: "已经，早已；先前", type: "adv" }],
  },
  {
    word: "also",
    translations: [
      { translation: "也；而且；同样", type: "adv" },
      { translation: "并且；另外", type: "conj" },
      { translation: "(Also)人名；(罗)阿尔索", type: "n" },
    ],
    phrases: [
      { phrase: "but also", translation: "不仅……而且…… 并且；表强调" },
      { phrase: "as also", translation: "同样；照样" },
      { phrase: "see also", translation: "参见；另请参阅" },
      { phrase: "also notify", translation: "另请通知" },
    ],
  },
  {
    word: "although",
    translations: [{ translation: "尽管；虽然；但是；然而", type: "conj" }],
  },
  {
    word: "always",
    translations: [{ translation: "永远，一直；总是；常常", type: "adv" }],
    phrases: [
      { phrase: "as always", translation: "◎同平时一样" },
      { phrase: "almost always", translation: "几乎总是；通常" },
      { phrase: "always ready", translation: "随时候命（电视剧）" },
      { phrase: "always the case", translation: "常常如此" },
      { phrase: "always on top", translation: "总在最上面" },
      { phrase: "always online", translation: "永远在线；随时在线" },
      { phrase: "since always", translation: "一向，一向以来，一直" },
    ],
  },
  {
    word: "America",
    translations: [
      { translation: "美洲（包括北美和南美洲）；美国", type: "n" },
    ],
    phrases: [
      { phrase: "north america", translation: "北美洲" },
      { phrase: "south america", translation: "南美洲" },
      { phrase: "latin america", translation: "拉丁美洲" },
      {
        phrase: "united states of america",
        translation: "美利坚合众国（美国）",
      },
      { phrase: "bank of america", translation: "n. 美国银行" },
      {
        phrase: "central america",
        translation: "中美洲（位于墨西哥与南美洲之间）；中美洲各国",
      },
      { phrase: "corporate america", translation: "美国公司" },
      { phrase: "voice of america", translation: "美国之音" },
      { phrase: "america online", translation: "美国在线服务公司" },
      {
        phrase: "good morning america",
        translation: "早安美国（美国广播公司早间节目的名称）",
      },
      { phrase: "confederate states of america", translation: "美利坚联盟国" },
      { phrase: "middle america", translation: "中美洲（墨西哥及美洲中部）" },
      {
        phrase: "british north america",
        translation: "英属北美；英国保险公会北美洲保险区域",
      },
    ],
  },
  {
    word: "American",
    translations: [
      { translation: "美国人，美洲人；美国英语", type: "n" },
      { translation: "美国的，美洲的；地道美国式的", type: "adj" },
    ],
    phrases: [
      { phrase: "south american", translation: "南美洲的；南美洲人的" },
      { phrase: "american culture", translation: "美国文化" },
      { phrase: "american english", translation: "美式英语" },
      { phrase: "native american", translation: "印第安人；美洲原住民" },
      { phrase: "latin american", translation: "拉丁美洲的" },
      { phrase: "american dream", translation: "美国梦" },
      { phrase: "chinese american", translation: "美籍华人；华裔美国人" },
      {
        phrase: "african american",
        translation:
          "非裔美国人（指美国黑人）；非裔美籍（等于African American）",
      },
      {
        phrase: "american idol",
        translation: "美国偶像（美国真人秀电视节目）",
      },
      {
        phrase: "american express",
        translation: "美国运通（财富500强公司之一，总部所在地美国）",
      },
      { phrase: "american revolution", translation: "美国独立战争" },
      { phrase: "american indian", translation: "美洲印第安人" },
      { phrase: "american football", translation: "美式橄榄球" },
      { phrase: "all american", translation: "全美国的" },
      { phrase: "american airlines", translation: "美国航空公司" },
      { phrase: "american ginseng", translation: "西洋参" },
      { phrase: "american civil war", translation: "n. 美国内战" },
      {
        phrase: "american international group",
        translation: "美国国际集团，美国国际集团公司",
      },
      { phrase: "american system", translation: "美制；美国体系" },
      { phrase: "asian american", translation: "亚裔美国人" },
    ],
  },
  {
    word: "among",
    translations: [{ translation: "在…中间；在…之中", type: "prep" }],
    phrases: [
      { phrase: "from among", translation: "从…中间；从…当中" },
      { phrase: "among others", translation: "其中；尤其；除了别的之外" },
      { phrase: "among the rest", translation: "adv. 在其中" },
      { phrase: "among the number", translation: "在其中，包括在内" },
    ],
  },
  {
    word: "ancient",
    translations: [
      { translation: "古代的；古老的，过时的；年老的", type: "adj" },
      { translation: "古代人；老人", type: "n" },
    ],
    phrases: [
      { phrase: "ancient chinese", translation: "n. 古代汉语" },
      { phrase: "ancient times", translation: "古代，上古" },
      { phrase: "ancient city", translation: "古都" },
      { phrase: "in ancient times", translation: "在古代" },
      { phrase: "ancient greece", translation: "古希腊" },
      { phrase: "ancient greek", translation: "古希腊语" },
      { phrase: "ancient civilization", translation: "古代文明；远古文化" },
      { phrase: "ancient and modern", translation: "古今" },
      { phrase: "ancient capital", translation: "古都" },
      { phrase: "ancient history", translation: "西洋古代史；家喻户晓的故事" },
      { phrase: "ancient literature", translation: "古代文学" },
      { phrase: "ancient architecture", translation: "古代建筑" },
      { phrase: "ancient world", translation: "远古世纪" },
      { phrase: "ancient chinese literature", translation: "中国古代文学" },
      { phrase: "ancient relics", translation: "古代遗物，古迹" },
      { phrase: "ancient coins", translation: "古钱币" },
      { phrase: "history of ancient china", translation: "中国古代史" },
      { phrase: "ancient porcelain", translation: "古瓷" },
    ],
  },
  {
    word: "and",
    translations: [
      { translation: "和，与；就；而且；但是；然后", type: "conj" },
      { translation: "(And)人名；(土、瑞典)安德", type: "n" },
    ],
    phrases: [
      { phrase: "and so", translation: "因此；所以" },
      { phrase: "and then", translation: "于是，然后" },
      { phrase: "and so on", translation: "等等；诸如此类" },
      { phrase: "and some", translation: "还有别的；还不止这些；比这个还要多" },
      { phrase: "and all", translation: "等等；的确；此外；连…一齐都" },
      { phrase: "and now", translation: "那么；那么现在" },
      {
        phrase: "and found",
        translation: "[美国英语](工资以外)供给膳宿[亦作 all found]",
      },
      { phrase: "and yet", translation: "可是，然而" },
      { phrase: "in and out", translation: "进进出出；来来去去" },
      { phrase: "and one's train", translation: "及其同类" },
      { phrase: "and the like", translation: "等等；依次类推" },
      { phrase: "and reason", translation: "这也是有道理的" },
      { phrase: "and things", translation: "[口语]等等之类" },
      { phrase: "and vice versa", translation: "反之亦然；反过来也一样" },
      { phrase: "and them", translation: "等人" },
      { phrase: "and then some", translation: "至少；而且还远不止此" },
      { phrase: "and stuff", translation: "等等；诸如此类" },
      {
        phrase: "and what not",
        translation:
          "诸如此类（等于and 等等（等于what have you）；what have you或what not）",
      },
      { phrase: "up and up", translation: "越来越好；诚实" },
      {
        phrase: "and what have you",
        translation: "[口语]等等[见 what 中的 what have you ]",
      },
    ],
  },
  {
    word: "angry",
    translations: [
      { translation: "生气的；愤怒的；狂暴的；（伤口等）发炎的", type: "adj" },
    ],
    phrases: [
      { phrase: "angry with", translation: "生某人的气" },
      { phrase: "get angry", translation: "生气，发怒；变得生气" },
      { phrase: "angry at", translation: "发怒；为…生气" },
      { phrase: "angry about", translation: "因…生气" },
      { phrase: "be angry with someone", translation: "生某人的气" },
      { phrase: "get angry with", translation: "生某人的气" },
      { phrase: "get angry at", translation: "对...生气（发怒）" },
    ],
  },
  {
    word: "animal",
    translations: [{ translation: "动物", type: "n" }],
    phrases: [
      { phrase: "animal husbandry", translation: "畜牧业；畜牧学" },
      { phrase: "animal feed", translation: "动物饲料" },
      { phrase: "wild animal", translation: "n. 野生动物；野兽" },
      { phrase: "animal experiment", translation: "动物实验；动物试验" },
      { phrase: "animal rights", translation: "动物权利" },
      { phrase: "animal world", translation: "动物世界" },
      { phrase: "animal protection", translation: "动物保护" },
      { phrase: "domestic animal", translation: "家畜" },
      { phrase: "animal science", translation: "动物科学；畜牧学" },
      { phrase: "animal fat", translation: "动物脂；动物油脂" },
      { phrase: "animal kingdom", translation: "n. 动物界" },
      { phrase: "experimental animal", translation: "[医]实验动物" },
      { phrase: "animal food", translation: "动物性食品；动物饲料" },
      { phrase: "animal protein", translation: "动物蛋白" },
      { phrase: "animal life", translation: "动物生命" },
      { phrase: "laboratory animal", translation: "试验动物" },
      { phrase: "animal nutrition", translation: "动物营养学" },
      { phrase: "animal waste", translation: "动物粪便" },
      { phrase: "animal breeding", translation: "动物育种；家畜育种" },
      { phrase: "rare animal", translation: "稀有动物" },
    ],
  },
  {
    word: "another",
    translations: [
      { translation: "又一，另一；另外的；不同的", type: "adj" },
      { translation: "另一个；又一个", type: "pron" },
      { translation: "另一个；另一个人", type: "prep" },
    ],
    phrases: [
      { phrase: "one another", translation: "彼此，互相" },
      { phrase: "for another", translation: "第二；其次" },
      { phrase: "one after another", translation: "adv. 接连地；一个接一个地" },
      { phrase: "another one", translation: "另一个" },
      { phrase: "yet another", translation: "adv. 另一种" },
      {
        phrase: "one way or another",
        translation: "adv. 无论如何；以某种方法",
      },
      { phrase: "such another", translation: "同种类中的另一个[见 such]" },
    ],
  },
  {
    word: "answer",
    translations: [
      { translation: "回答；符合", type: "v" },
      { translation: "回答；答案；答辩", type: "n" },
    ],
    phrases: [
      { phrase: "in answer to", translation: "回答；应…要求" },
      { phrase: "answer for", translation: "因……而受罚；对……负责" },
      { phrase: "no answer", translation: "无应答；舵失灵" },
      { phrase: "answer the phone", translation: "接电话" },
      { phrase: "answer the following questions", translation: "回答下列问题" },
      { phrase: "wrong answer", translation: "答案错误" },
      { phrase: "answer sheet", translation: "n. 答案纸" },
      { phrase: "short answer", translation: "简答题；简短回答" },
      { phrase: "answer the telephone", translation: "接电话" },
      { phrase: "immediate answer", translation: "立即应答" },
      { phrase: "answer back", translation: "应答，回复；顶嘴" },
      {
        phrase: "know all the answers",
        translation: "见多识广；自命不凡；好象什么都知道的样子",
      },
      {
        phrase: "soft answer",
        translation: "温和的回答；轻轻的回答；委婉的回答",
      },
      { phrase: "answer key", translation: "答案；题解；练习答案（解答）" },
      { phrase: "answer the needs of", translation: "满足...需要" },
      { phrase: "answer up", translation: "迅速回答" },
      {
        phrase: "answer phone",
        translation: "留言机，电话录音机；电话留言；接电话",
      },
    ],
  },
  {
    word: "ant",
    translations: [{ translation: "蚂蚁", type: "n" }],
    phrases: [{ phrase: "fire ant", translation: "火蚁" }],
  },
  {
    word: "any",
    translations: [
      { translation: "任何的；所有的；丝毫", type: "adj" },
      { translation: "任何；任何一个；若干", type: "pron" },
      { translation: "稍微；少许", type: "adv" },
      { translation: "(Any)人名；(法、罗)阿尼", type: "n" },
    ],
  },
  {
    word: "anyone",
    translations: [{ translation: "任何人；任何一个", type: "pron" }],
  },
  {
    word: "anything",
    translations: [{ translation: "任何事", type: "pron" }],
    phrases: [
      { phrase: "anything but", translation: "根本不，决不" },
      { phrase: "of anything", translation: "或者其他别的事，或其他什么的" },
      { phrase: "for anything", translation: "无论如何（用于否定句中）" },
      { phrase: "if anything", translation: "如果有什么区别的话" },
      { phrase: "anything like", translation: "多少有点像" },
      {
        phrase: "see anything",
        translation: "[委婉语](女子)见潮红，来例假[系“有喜了”的委婉说法]",
      },
      { phrase: "anything to do with", translation: "与…有关系" },
      {
        phrase: "anything of",
        translation: "（用于疑问或条件句）多多少少；一点…的味儿；很少",
      },
      {
        phrase: "like anything",
        translation: "[口]拼命地；非常猛地；全力地；象什么似的",
      },
      { phrase: "as anything", translation: "象什么似的；非常" },
      { phrase: "anything goes", translation: "怎么都行；任何事情都可能发生" },
      {
        phrase: "good for anything",
        translation: "胜任各项工作；对一切都适用",
      },
    ],
  },
  {
    word: "anyway",
    translations: [{ translation: "无论如何，不管怎样；总之", type: "adv" }],
  },
  {
    word: "anywhere",
    translations: [
      { translation: "在任何地方；无论何处", type: "adv" },
      { translation: "任何地方", type: "n" },
    ],
    phrases: [
      { phrase: "or anywhere", translation: "或是什么别的地方，或其他某地" },
      { phrase: "get anywhere", translation: "有点成就" },
      { phrase: "anywhere near", translation: "[口]接近于；全然；差不多" },
      { phrase: "anywhere is", translation: "无处不在；任何地方都是如此" },
      { phrase: "anywhere you go", translation: "到处" },
      {
        phrase: "if anywhere",
        translation: "如果有什么地方的话，如果在哪儿能…的话",
      },
    ],
  },
  {
    word: "appear",
    translations: [{ translation: "出现；显得；似乎；出庭；登场", type: "v" }],
    phrases: [
      { phrase: "appear in", translation: "出现在…" },
      { phrase: "appear on", translation: "在...上出现" },
      { phrase: "appear to be", translation: "好像是；仿佛" },
      { phrase: "appear under", translation: "以…出现" },
    ],
  },
  {
    word: "apple",
    translations: [
      {
        translation:
          "苹果，苹果树，苹果似的东西；[美俚]炸弹，手榴弹，（棒球的）球；[美俚]人，家伙。",
        type: "n",
      },
    ],
    phrases: [
      { phrase: "an apple", translation: "一个苹果" },
      { phrase: "apple tree", translation: "苹果树" },
      { phrase: "apple juice", translation: "苹果汁" },
      { phrase: "apple pie", translation: "苹果派；苹果馅饼" },
      { phrase: "big apple", translation: "n. [俚]美国纽约城" },
      { phrase: "red apple", translation: "红苹果" },
      { phrase: "apple cider", translation: "苹果酒，苹果汁；苹果醋" },
      { phrase: "green apple", translation: "青苹果" },
      { phrase: "apple vinegar", translation: "苹果醋" },
      { phrase: "apples and oranges", translation: "风马牛不相及的事物" },
      { phrase: "apple computer", translation: "苹果电脑；苹果电脑公司" },
      {
        phrase: "apple of discord",
        translation:
          "不和的金苹果；引起不和的争端；不和的种子；祸根（据希腊神话三女神因争金苹果而导致特洛伊战争）",
      },
      { phrase: "bad apple", translation: "坏家伙" },
      { phrase: "an apple of discord", translation: "争端；祸根" },
      {
        phrase: "apple of sodom",
        translation: "金玉其外，败絮其中；徒具其表而无其实之物",
      },
      { phrase: "golden apple", translation: "金苹果；黄绿苹果" },
      { phrase: "rotten apple", translation: "[美俚]坏家伙" },
      {
        phrase: "apple of the eye",
        translation: "瞳子；极珍爱之人；极珍爱之物",
      },
      { phrase: "apple blossom", translation: "苹果花" },
      { phrase: "apple sauce", translation: "苹果酱；苹果泥" },
    ],
  },
  {
    word: "April",
    translations: [{ translation: "四月", type: "n" }],
    phrases: [
      { phrase: "april fool's day", translation: "愚人节（4月1日）" },
      { phrase: "april fool", translation: "愚人节；愚人节中受愚弄者" },
      { phrase: "april fools' day", translation: "愚人节" },
    ],
  },
  {
    word: "area",
    translations: [{ translation: "区域，地区；面积；范围", type: "n" }],
    phrases: [
      { phrase: "in the area", translation: "在这个地区；在该领域" },
      { phrase: "in the area of", translation: "在…领域" },
      { phrase: "rural area", translation: "农村地区；乡郊地区" },
      { phrase: "mining area", translation: "矿山；布雷区；采矿区" },
      { phrase: "surface area", translation: "表面面积；曲面面积" },
      { phrase: "urban area", translation: "城市地区" },
      { phrase: "research area", translation: "研究方向" },
      { phrase: "residential area", translation: "住宅区，居民区" },
      { phrase: "in area", translation: "在面积上；从面积上讲；在区域中" },
      { phrase: "mountain area", translation: "山区" },
      { phrase: "construction area", translation: "施工区[建]" },
      { phrase: "sea area", translation: "海域；海区" },
      { phrase: "land area", translation: "陆地区域；合模面面积；接触面积" },
      { phrase: "local area network", translation: "n. 局域网" },
      { phrase: "development area", translation: "开发区" },
      { phrase: "total area", translation: "n. 总面积" },
      { phrase: "specific surface area", translation: "比表面积" },
      { phrase: "developed area", translation: "[机]展开面积" },
      { phrase: "border area", translation: "边境区域" },
      { phrase: "water area", translation: "水域，水的面积" },
    ],
  },
  {
    word: "arm",
    translations: [
      { translation: "手臂；武器；袖子；装备；部门", type: "n" },
      { translation: "武装起来", type: "v" },
    ],
    phrases: [
      { phrase: "in arms", translation: "怀抱着的；武装起来的" },
      { phrase: "on one's arm", translation: "由(或靠)手臂支撑着" },
      { phrase: "up in arms", translation: "竭力反对；进行武装斗争" },
      { phrase: "at arm's length", translation: "疏远；在手臂伸得到的地方" },
      { phrase: "right arm", translation: "右臂；得力助手" },
      { phrase: "with open arms", translation: "张开双臂；热情地；亲切地" },
      { phrase: "on the arm", translation: "[美国俚语]" },
      { phrase: "arm in arm", translation: "臂挽臂" },
      { phrase: "upper arm", translation: "上臂" },
      { phrase: "bear arms", translation: "携带武器；当兵" },
      { phrase: "with arms", translation: "武装的" },
      { phrase: "under his arm", translation: "（腋下）挟着" },
      { phrase: "robot arm", translation: "机械手臂；机器手" },
      { phrase: "long arm", translation: "长臂" },
      { phrase: "rocker arm", translation: "摇臂，摇杆" },
      { phrase: "swing arm", translation: "摇动臂" },
      { phrase: "control arm", translation: "n. 控制杆，操作杆" },
      {
        phrase: "arm of the law",
        translation: "[讽刺语]执法人(如警察、法官、律师等)",
      },
      { phrase: "take up arms", translation: "v. 拿起武器" },
      {
        phrase: "suspension arm",
        translation: "吊臂；弹簧吊架；悬挂臂，悬架臂",
      },
    ],
  },
  {
    word: "army",
    translations: [{ translation: "陆军，军队", type: "n" }],
    phrases: [
      { phrase: "red army", translation: "n. 红军" },
      { phrase: "in the army", translation: "在陆军中" },
      { phrase: "join the army", translation: "参军" },
      { phrase: "army group", translation: "集团军群" },
      { phrase: "salvation army", translation: "[基督]救世军" },
      { phrase: "army man", translation: "军人" },
      { phrase: "field army", translation: "n. 野战军" },
      { phrase: "standing army", translation: "常备军；现役部队" },
      { phrase: "united states army", translation: "美国陆军" },
      { phrase: "regular army", translation: "正规军；常备军" },
      { phrase: "army base", translation: "陆军基地" },
      { phrase: "serve in the army", translation: "服兵役" },
      { phrase: "army day", translation: "中国人民解放军建军节" },
      { phrase: "continental army", translation: "[美国历史]大陆军" },
      { phrase: "general of the army", translation: "（美）陆军五星上将" },
      { phrase: "irish republican army", translation: "爱尔兰共和军" },
    ],
  },
  {
    word: "around",
    translations: [
      { translation: "大约；到处；在附近", type: "adv" },
      { translation: "四处；在…周围", type: "prep" },
    ],
    phrases: [
      { phrase: "all around", translation: "周围；到处，四处" },
      { phrase: "around here", translation: "附近；在这周围" },
      { phrase: "go around", translation: "四处走动；供应；（消息）流传" },
      { phrase: "in and around", translation: "在…的内部及周边" },
      {
        phrase: "have been around",
        translation: "[美口]阅历多；老于世故；遍布各地",
      },
    ],
  },
  {
    word: "arrive",
    translations: [
      { translation: "到达；成功；达成；出生", type: "v" },
      { translation: "(Arrive)人名；(法)阿里夫", type: "n" },
    ],
    phrases: [
      { phrase: "arrive at", translation: "达到，达成；到达某地" },
      { phrase: "arrive in", translation: "抵达，到达" },
      { phrase: "arrive from", translation: "从某地来（这里）" },
      { phrase: "arrive on", translation: "到达" },
      { phrase: "arrive home", translation: "到家" },
      { phrase: "arrive at a conclusion", translation: "得出一个结论" },
      { phrase: "arrive at a decision", translation: "决定下来" },
      { phrase: "to arrive late", translation: "迟到" },
    ],
  },
  {
    word: "art",
    translations: [
      { translation: "艺术；美术；艺术品", type: "n" },
      { translation: "艺术的；艺术品的", type: "adj" },
      { translation: "是（be的变体）", type: "v" },
    ],
    phrases: [
      { phrase: "contemporary art", translation: "当代艺术" },
      { phrase: "works of art", translation: "艺术品" },
      { phrase: "literature and art", translation: "文艺；文学与艺术" },
      {
        phrase: "modern art",
        translation: "现代艺术；当代艺术；现代美术；近代艺术",
      },
      { phrase: "state of the art", translation: "当前发展状况，目前发展水平" },
      { phrase: "art design", translation: "艺术设计；美术设计" },
      { phrase: "folk art", translation: "民间艺术" },
      { phrase: "art education", translation: "艺术教育；美术教育" },
      {
        phrase: "art form",
        translation: "艺术形式（尤指文学，绘画，音乐，民歌等）",
      },
      { phrase: "fine art", translation: "精细工艺" },
      { phrase: "work of art", translation: "艺术品" },
      { phrase: "art history", translation: "艺术史" },
      { phrase: "art museum", translation: "美术馆，美术博物馆；艺术博物馆" },
      { phrase: "prior art", translation: "先前技术" },
      { phrase: "art gallery", translation: "美术馆；画廊" },
      {
        phrase: "art work",
        translation: "艺术作品；工艺品；布线图；原图，图模",
      },
      { phrase: "martial art", translation: "武术（源于东方的几种搏斗技巧）" },
      { phrase: "art exhibition", translation: "艺术展览；美术展览" },
      { phrase: "art school", translation: "艺术学校" },
      { phrase: "public art", translation: "公共艺术" },
    ],
  },
  {
    word: "article",
    translations: [
      { translation: "文章；物品；条款；[语] 冠词", type: "n" },
      {
        translation: "订约将…收为学徒或见习生；使…受协议条款的约束",
        type: "v",
      },
    ],
    phrases: [
      {
        phrase: "in articles",
        translation: "根据契约当学徒，依雇用契约工作着",
      },
      { phrase: "write an article", translation: "写文章" },
      { phrase: "first article", translation: "首产品" },
      { phrase: "an article of", translation: "一件（衣服）" },
      { phrase: "handicraft article", translation: "工艺美术品" },
      { phrase: "journal article", translation: "期刊论文；期刊文章" },
      { phrase: "jade article", translation: "玉器" },
      { phrase: "feature article", translation: "特写；专题文章；深度文章" },
      { phrase: "definite article", translation: "定冠词the" },
      { phrase: "article of faith", translation: "信念；信条" },
      { phrase: "article number", translation: "商品号；货号" },
      { phrase: "article of association", translation: "公司章程" },
      { phrase: "leading article", translation: "主要文章；头条新闻" },
      {
        phrase: "article by article",
        translation:
          "一件复一件 articles(或 objects) of virtu 艺术珍品,古玩,古董",
      },
    ],
  },
  {
    word: "as",
    translations: [
      { translation: "因为；随着；虽然；依照；当…时", type: "conj" },
      { translation: "如同；当作；以…的身份", type: "prep" },
      { translation: "同样地；和…一样的", type: "adv" },
    ],
    phrases: [
      { phrase: "as well", translation: "也；同样地；还不如" },
      { phrase: "as well as", translation: "也；和…一样；不但…而且" },
      { phrase: "as one", translation: "一致的" },
      { phrase: "as soon", translation: "◎宁愿…，宁可…" },
      { phrase: "as soon as", translation: "一…就…" },
      { phrase: "as long as", translation: "只要；和…一样长" },
      { phrase: "as if", translation: "犹如，好似" },
      { phrase: "as much", translation: "也；同样多的" },
      { phrase: "as for", translation: "关于，至于" },
      { phrase: "as soon as possible", translation: "尽快" },
      { phrase: "as a whole", translation: "总的来说" },
      { phrase: "as far as", translation: "adv. 至于，直到，远到；就…而言" },
      { phrase: "as of", translation: "自……起" },
      { phrase: "as though", translation: "好像；仿佛" },
      { phrase: "as being", translation: "就是；即像" },
      { phrase: "as early as", translation: "早在…的时候" },
      { phrase: "as usual", translation: "像往常一样；照例" },
      { phrase: "as good as", translation: "和…几乎一样，实际上等于…" },
      { phrase: "as per", translation: "按照，依据；如同" },
      { phrase: "as such", translation: "同样地；本身；就其本身而论" },
    ],
  },
  {
    word: "Asia",
    translations: [{ translation: "亚洲", type: "n" }],
    phrases: [
      { phrase: "southeast asia", translation: "东南亚" },
      { phrase: "east asia", translation: "东亚" },
      { phrase: "asia pacific", translation: "亚太地区；亚太区" },
      { phrase: "south asia", translation: "n. 南亚" },
      { phrase: "central asia", translation: "中亚；亚洲中部" },
      { phrase: "asia minor", translation: "n. 小亚细亚" },
      { phrase: "financial crisis in asia", translation: "亚洲金融危机" },
    ],
  },
  {
    word: "Asian",
    translations: [
      { translation: "亚洲人", type: "n" },
      { translation: "亚洲的；亚洲人的", type: "adj" },
    ],
    phrases: [
      { phrase: "the asian games", translation: "亚运会" },
      { phrase: "asian development bank", translation: "亚洲开发银行" },
      { phrase: "asian american", translation: "亚裔美国人" },
      { phrase: "asian business", translation: "亚洲商业（杂志）" },
      { phrase: "asian values", translation: "亚洲价值观" },
    ],
  },
  {
    word: "ask",
    translations: [
      { translation: "问，询问；要求；需要；邀请；讨价", type: "v" },
      { translation: "(Ask)人名；(芬、瑞典)阿斯克", type: "n" },
    ],
  },
  {
    word: "asleep",
    translations: [
      { translation: "睡着的；麻木的；长眠的", type: "adj" },
      { translation: "熟睡地；进入睡眠状态", type: "adv" },
    ],
    phrases: [
      { phrase: "fall asleep", translation: "v. 入睡；睡着" },
      { phrase: "fell asleep", translation: "睡着了；入睡" },
      { phrase: "fast asleep", translation: "熟睡的；很快地入睡" },
      { phrase: "fallen asleep", translation: "睡着了" },
      { phrase: "sound asleep", translation: "睡熟" },
      { phrase: "lay asleep", translation: "◎使…入睡" },
    ],
  },
  {
    word: "at",
    translations: [
      {
        translation:
          "在（表示存在或出现的地点、场所、位置、空间）；以（某种价格、速度等）；向；达；因为；朝；忙于",
        type: "prep",
      },
      {
        translation:
          "阿特（老挝货币基本单位att）；[化]砹（极不稳定放射性元素）",
        type: "n",
      },
      {
        translation: "密封的（airtight）；气温（air temperature）",
        type: "abbr",
      },
    ],
    phrases: [
      { phrase: "at all", translation: "（否定句）根本；究竟" },
      { phrase: "be in at", translation: "在场，参与" },
      {
        phrase: "at it again",
        translation:
          "[口语]争吵；重复负面消极的行为(此语亦可含有与性行为有关的意思)",
      },
    ],
  },
  {
    word: "Atlantic",
    translations: [
      { translation: "大西洋", type: "n" },
      { translation: "大西洋的", type: "adj" },
    ],
    phrases: [
      { phrase: "atlantic ocean", translation: "大西洋" },
      {
        phrase: "atlantic city",
        translation: "大西洋城（美国新泽西州东南部）",
      },
      { phrase: "north atlantic treaty", translation: "北大西洋公约" },
      {
        phrase: "north atlantic treaty organization",
        translation: "北大西洋公约组织（等于NATO）",
      },
      { phrase: "atlantic salmon", translation: "大西洋鲑鱼" },
      { phrase: "virgin atlantic", translation: "英国维珍大西洋航空公司" },
      { phrase: "atlantic charter", translation: "n. 大西洋宪章" },
    ],
  },
  {
    word: "attention",
    translations: [{ translation: "注意力；关心；立正！（口令）", type: "n" }],
    phrases: [
      { phrase: "pay attention", translation: "专心；集中注意力" },
      { phrase: "pay more attention to", translation: "更加注意" },
      { phrase: "pay close attention to", translation: "密切注意" },
      { phrase: "be paid attention to", translation: "关心" },
      { phrase: "give one's attention to", translation: "v. 注意" },
      { phrase: "give attention to", translation: "考虑；注意；关心" },
      { phrase: "public attention", translation: "公众的关注" },
      { phrase: "attract attention", translation: "vi. 引起……的注意" },
      { phrase: "for your attention", translation: "请你注意；您的关照" },
      { phrase: "draw attention", translation: "引起注意" },
      { phrase: "with attention", translation: "adj. 留心地，注意地" },
      { phrase: "medical attention", translation: "医疗照顾；医疗看护" },
      { phrase: "immediate attention", translation: "注视；及时关注" },
      { phrase: "pay no attention to", translation: "不注意，不在意" },
      { phrase: "matters need attention", translation: "注意事项" },
      { phrase: "call attention to", translation: "唤起注意" },
      { phrase: "prompt attention", translation: "从速办理" },
      { phrase: "undivided attention", translation: "一心一意" },
      { phrase: "attention span", translation: "注意广度；注意力的持续时间" },
      {
        phrase: "attention deficit hyperactivity disorder",
        translation: "过动症，注意力不足过动症；过度活跃症",
      },
    ],
  },
  {
    word: "August",
    translations: [
      { translation: "威严的；令人敬畏的", type: "adj" },
      { translation: "八月（简写为Aug）", type: "n" },
    ],
  },
  {
    word: "aunt",
    translations: [{ translation: "阿姨；姑妈；伯母；舅妈", type: "n" }],
    phrases: [
      { phrase: "paternal aunt", translation: "姑母" },
      { phrase: "agony aunt", translation: "（英）问答专栏阿姨；心理咨询阿姨" },
      { phrase: "great aunt", translation: "叔祖母" },
    ],
  },
  {
    word: "Australia",
    translations: [{ translation: "澳大利亚，澳洲", type: "n" }],
    phrases: [
      { phrase: "south australia", translation: "南澳大利亚" },
      {
        phrase: "western australia",
        translation:
          "西澳大利亚州；西澳洲（澳大利亚联邦的一个洲，位于澳大利亚西部）",
      },
      { phrase: "commonwealth of australia", translation: "澳大利亚联邦" },
      {
        phrase: "reserve bank of australia",
        translation: "澳大利亚储备银行（澳大利亚中央银行）",
      },
      { phrase: "australia day", translation: "澳大利亚日；澳洲国庆日" },
      { phrase: "commonwealth bank of australia", translation: "澳洲联邦银行" },
    ],
  },
  {
    word: "Australian",
    translations: [
      { translation: "澳大利亚的，澳大利亚人的", type: "adj" },
      { translation: "澳大利亚人", type: "n" },
    ],
    phrases: [
      {
        phrase: "australian national university",
        translation: "澳大利亚国立大学",
      },
      { phrase: "australian dollar", translation: "澳币" },
      {
        phrase: "australian shepherd",
        translation: "n. 澳大利亚牧羊犬；澳洲牧羊犬",
      },
      { phrase: "australian football", translation: "澳式足球" },
      { phrase: "australian aborigine", translation: "澳大利亚原住民" },
    ],
  },
  {
    word: "autumn",
    translations: [
      { translation: "秋天；成熟期；渐衰期，凋落期", type: "n" },
      { translation: "秋天的，秋季的", type: "adj" },
    ],
    phrases: [
      { phrase: "in autumn", translation: "在秋天" },
      { phrase: "spring and autumn", translation: "春秋" },
      { phrase: "spring and autumn period", translation: "春秋时代" },
      { phrase: "autumn leaves", translation: "秋天的落叶" },
      { phrase: "autumn wind", translation: "秋风" },
      { phrase: "late autumn", translation: "深秋；晚秋；秋日和" },
      { phrase: "spring and autumn annals", translation: "春秋（中国史书）" },
    ],
  },
  {
    word: "available",
    translations: [
      { translation: "可获得的；可购得的；可找到的；有空的", type: "adj" },
    ],
    phrases: [
      {
        phrase: "available for",
        translation: "可用于…的；对…有效的；能参加…的",
      },
      { phrase: "available on", translation: "仅在…有效（付款）" },
      { phrase: "available from", translation: "可向…购买" },
      { phrase: "available with", translation: "向（指定银行）押汇" },
      { phrase: "available resources", translation: "可利用的资源" },
      { phrase: "commercially available", translation: "市场上可买到的" },
      { phrase: "available data", translation: "现有数据；可用数据" },
      { phrase: "available information", translation: "可利用信息" },
      { phrase: "make available", translation: "使有用；使可用到" },
      { phrase: "available water", translation: "有效水分" },
      { phrase: "space available", translation: "可用空间" },
      { phrase: "available energy", translation: "有效能；可用能" },
      { phrase: "available time", translation: "可用时间；有效时间" },
      { phrase: "available funds", translation: "可用基金；可动用的资金" },
      { phrase: "available memory", translation: "可用内存" },
      { phrase: "available capacity", translation: "有效容积；可用功率" },
      {
        phrase: "available material",
        translation: "可用物料；可用材料；良品可使用",
      },
      { phrase: "available work", translation: "[物]可用功，可利用工时" },
      { phrase: "available light", translation: "[美术][摄影术]自然光线" },
    ],
  },
  {
    word: "avoid",
    translations: [{ translation: "避免；避开，躲避；消除", type: "v" }],
    phrases: [{ phrase: "avoid doing", translation: "避免做某事；逃避…" }],
  },
  {
    word: "away",
    translations: [{ translation: "离去，离开；在远处", type: "adv" }],
    phrases: [
      { phrase: "away from", translation: "远离，离开；避开痛苦" },
      { phrase: "far away", translation: "遥远的" },
      { phrase: "right away", translation: "立刻" },
      { phrase: "away with", translation: "◎把(物)拿走；去掉；把(人)带走" },
      { phrase: "far away from", translation: "远离；离…远" },
      { phrase: "go away", translation: "走开" },
      { phrase: "straight away", translation: "马上；即刻" },
      { phrase: "do away with", translation: "v. 废除，去掉；弄死" },
      { phrase: "away from her", translation: "柳暗花明（电影名称）" },
      { phrase: "far and away", translation: "无疑地；显然地" },
      { phrase: "away from it all", translation: "远离尘嚣" },
      { phrase: "out and away", translation: "大大地，远远地" },
    ],
  },
  {
    word: "baby",
    translations: [
      { translation: "婴儿，婴孩；孩子气的人", type: "n" },
      { translation: "纵容，娇纵；把……当婴儿般对待", type: "v" },
      { translation: "婴儿的；幼小的", type: "adj" },
    ],
    phrases: [
      { phrase: "baby girl", translation: "女婴；小女孩" },
      { phrase: "have a baby", translation: "生孩子" },
      { phrase: "baby boy", translation: "男婴；小男孩" },
      { phrase: "baby boom", translation: "婴儿潮；生育高峰" },
      { phrase: "baby food", translation: "婴儿食品；儿童食品" },
      { phrase: "baby formula", translation: "婴幼儿配方奶粉；婴幼儿配方" },
      {
        phrase: "baby carriage",
        translation: "婴儿车；童车（等于baby buggy，carriage）",
      },
      { phrase: "baby stroller", translation: "婴儿推车" },
      {
        phrase: "come on baby",
        translation: "宝宝总动员（一款韩国街机游戏）；来吧宝贝儿",
      },
      { phrase: "baby teeth", translation: "乳牙" },
      { phrase: "baby blue", translation: "n. 淡蓝色" },
      {
        phrase: "baby shower",
        translation: "宝宝派对（在孩子出生前举办的特殊派对）",
      },
      { phrase: "baby face", translation: "n. 娃娃脸" },
      { phrase: "baby talk", translation: "儿语" },
      { phrase: "baby sitter", translation: "临时替人看小孩者；照顾婴孩者" },
      { phrase: "baby carrier", translation: "童车；婴儿背带；轻型航空母舰" },
      { phrase: "baby car", translation: "微型小客车" },
      { phrase: "baby wear", translation: "婴儿装" },
      { phrase: "test-tube baby", translation: "n. [医]试管婴儿" },
      { phrase: "tiny baby", translation: "个儿小的婴儿" },
    ],
  },
  {
    word: "back",
    translations: [
      {
        translation: "后面；背部；靠背；足球等的后卫；书报等的末尾",
        type: "n",
      },
      { translation: "支持；后退；背书；下赌注", type: "v" },
      { translation: "以前；向后地；来回地；上溯；回来；回原处", type: "adv" },
      { translation: "后面的；过去的；拖欠的", type: "adj" },
    ],
    phrases: [
      { phrase: "go back", translation: "回去；追溯" },
      { phrase: "back in", translation: "[体育]后内刃" },
      { phrase: "back of", translation: "在…后面；在…背后" },
      { phrase: "back on", translation: "背靠" },
      { phrase: "back into", translation: "倒车撞上（某物）" },
      { phrase: "in the back", translation: "在后面" },
      { phrase: "at the back", translation: "在后面；在…后部" },
      { phrase: "back and forth", translation: "反复地，来回地" },
      {
        phrase: "back up",
        translation: "v. 支持，援助；（资料）备份；倒退；裱",
      },
      { phrase: "way back", translation: "好久以前，老早就" },
      { phrase: "on the back of", translation: "在…之外，在…后面" },
      {
        phrase: "at the back of",
        translation: "在…背后，支持；在…的后面；在…的后部",
      },
      { phrase: "back down", translation: "放弃；让步" },
      { phrase: "in the back of", translation: "在……后面；在……之后" },
      { phrase: "back out", translation: "退出；收回" },
      { phrase: "on my back", translation: "在背上；找我麻烦，挑我毛病" },
      { phrase: "on one's back", translation: "卧病在床" },
      { phrase: "back off", translation: "后退；软化；减轻；卸下" },
      { phrase: "back to back", translation: "背靠背；连续，紧接" },
      { phrase: "go back on", translation: "违背；背弃" },
    ],
  },
  {
    word: "background",
    translations: [
      { translation: "背景；隐蔽的位置", type: "n" },
      { translation: "作…的背景", type: "v" },
      { translation: "背景的；发布背景材料的", type: "adj" },
    ],
    phrases: [
      { phrase: "in the background", translation: "在后面，在幕后" },
      { phrase: "cultural background", translation: "文化背景" },
      {
        phrase: "educational background",
        translation: "学历；教育背景；教育程度",
      },
      { phrase: "social background", translation: "n. 社会背景" },
      { phrase: "background music", translation: "背景音乐；[电]陪衬音乐" },
      { phrase: "background information", translation: "背景资料；背景知识" },
      { phrase: "education background", translation: "学历；教育背景" },
      { phrase: "family background", translation: "家庭背景" },
      { phrase: "background noise", translation: "背景噪声" },
      { phrase: "background color", translation: "背景颜色" },
      {
        phrase: "academic background",
        translation: "学术背景；学历；教育背景",
      },
      { phrase: "background value", translation: "背景值" },
      { phrase: "background image", translation: "背景影像" },
      { phrase: "for background", translation: "（美）供内部参考" },
      { phrase: "white background", translation: "白色背景；比色板；比色纸" },
      {
        phrase: "on background",
        translation: "[美国、加拿大英语]仅供参考(不作援引)",
      },
      {
        phrase: "business background",
        translation: "工作经历；企业背景；事情履历",
      },
      { phrase: "political background", translation: "政治背景" },
      { phrase: "background radiation", translation: "背景辐射；[医]本底辐射" },
      { phrase: "background check", translation: "背景调查" },
    ],
  },
  {
    word: "bag",
    translations: [
      { translation: "袋；猎获物；（俚）一瓶啤酒", type: "n" },
      { translation: "猎获；把…装入袋中；占据，私吞；使膨大", type: "v" },
    ],
    phrases: [
      { phrase: "bags of", translation: "[俚语]许多的，充足的" },
      { phrase: "in the bag", translation: "十拿九稳的；稳操胜券的" },
      { phrase: "plastic bag", translation: "塑料袋；塑胶袋" },
      { phrase: "paper bag", translation: "纸袋子" },
      { phrase: "bag filter", translation: "袋式过滤器；袋滤器" },
      { phrase: "shopping bag", translation: "n. 购物袋" },
      { phrase: "filter bag", translation: "过滤袋" },
      { phrase: "sleeping bag", translation: "睡袋" },
      { phrase: "air bag", translation: "[机]气囊" },
      { phrase: "cosmetic bag", translation: "化妆包；化妆袋" },
      { phrase: "a bag of nails", translation: "颠三倒四；混乱" },
      { phrase: "tea bag", translation: "n. 茶叶袋" },
      { phrase: "hand bag", translation: "手提袋，手提包" },
      { phrase: "travel bag", translation: "旅行袋" },
      { phrase: "cloth bag", translation: "布袋" },
      {
        phrase: "bags under the eyes",
        translation: "[口语]眼睛下面的鼓胀，肿眼泡",
      },
      { phrase: "woven bag", translation: "编织袋；布袋；聚丙烯编织带" },
      { phrase: "laundry bag", translation: "洗衣袋" },
      { phrase: "vacuum bag", translation: "真空袋；真空加压袋" },
      { phrase: "ice bag", translation: "冰袋（用于身体消肿，镇痛）" },
    ],
  },
  {
    word: "ball",
    translations: [
      { translation: "球；舞会", type: "n" },
      { translation: "成团块", type: "v" },
    ],
    phrases: [
      { phrase: "ball mill", translation: "球磨；[机]球磨机" },
      {
        phrase: "on the ball",
        translation: "adv. [口]机灵；留心；有见识；勤奋",
      },
      { phrase: "ball valve", translation: "球阀，弹子阀；球形阀" },
      { phrase: "ball bearing", translation: "滚珠，钢球；滚珠轴承" },
      { phrase: "hit the ball", translation: "击球；顺利，成功" },
      { phrase: "steel ball", translation: "n. 钢珠" },
      { phrase: "play ball", translation: "开始活动；开始赛球" },
      { phrase: "ball screw", translation: "滚珠螺杆；滚珠丝杆；球头螺钉" },
      { phrase: "ball milling", translation: "球磨碾磨" },
      {
        phrase: "crystal ball",
        translation: "（占卜用的）水晶球；预言未来的方法",
      },
      { phrase: "rubber ball", translation: "橡皮球" },
      { phrase: "ball pen", translation: "圆珠笔" },
      { phrase: "golden ball", translation: "金球；金琥" },
      { phrase: "tennis ball", translation: "网球" },
      { phrase: "soccer ball", translation: "英式足球" },
      { phrase: "golf ball", translation: "高尔夫球" },
      { phrase: "ball rolling", translation: "钢球轧制" },
      { phrase: "cotton ball", translation: "棉球；硼钠钙石" },
      { phrase: "kick the ball", translation: "踢球" },
      { phrase: "pass the ball", translation: "[体育]传球" },
    ],
  },
  {
    word: "balloon",
    translations: [
      { translation: "激增；膨胀如气球", type: "v" },
      { translation: "气球", type: "n" },
      { translation: "像气球般鼓起的", type: "adj" },
    ],
    phrases: [
      { phrase: "air balloon", translation: "气球" },
      { phrase: "hot-air balloon", translation: "n. 热气球" },
      { phrase: "weather balloon", translation: "气象气球；探空气球" },
      {
        phrase: "balloon angioplasty",
        translation:
          "[外科学]气囊血管成形术；球囊成形术（等于percutaneous transluminal angioplasty）",
      },
      { phrase: "balloon pump", translation: "球囊泵；气囊泵" },
      { phrase: "balloon borne", translation: "球载反射器" },
      { phrase: "balloon flower", translation: "桔梗花" },
      {
        phrase: "like a lead balloon",
        translation: "毫无效果，毫无作用(意指如铅气球无法飞升)",
      },
      { phrase: "balloon catheter", translation: "气囊导管，气泡式导管" },
    ],
  },
  {
    word: "bamboo",
    translations: [
      { translation: "竹，竹子", type: "n" },
      { translation: "为…装上篾条", type: "vt" },
      { translation: "竹制的；土著居民的", type: "adj" },
    ],
    phrases: [
      { phrase: "bamboo shoot", translation: "竹笋，笋" },
      { phrase: "bamboo leaves", translation: "竹叶" },
      { phrase: "bamboo grove", translation: "竹林" },
      { phrase: "bamboo pole", translation: "竹枝" },
      {
        phrase: "bamboo curtain",
        translation: "竹幕（西方资产阶级舆论界过去对我国的诬蔑性用语）",
      },
      { phrase: "bamboo basket", translation: "竹篮；竹篓" },
      { phrase: "bamboo raft", translation: "竹筏；竹排" },
      { phrase: "bamboo fence", translation: "竹篱笆" },
    ],
  },
  {
    word: "banana",
    translations: [{ translation: "香蕉；喜剧演员；大鹰钩鼻", type: "n" }],
    phrases: [
      { phrase: "banana skin", translation: "香蕉皮；尴尬事" },
      {
        phrase: "top banana",
        translation: "主要滑稽演员，引申为最好的演员或重要的官员；主要人物",
      },
      {
        phrase: "banana split",
        translation: "香蕉圣代（剖开香蕉夹以冰淇淋等）；香蕉半剖条",
      },
      {
        phrase: "banana republic",
        translation: "n. 香蕉共和国（指中、南美洲发展中国家）",
      },
    ],
  },
  {
    word: "bank",
    translations: [
      { translation: "银行；岸；浅滩；储库", type: "n" },
      { translation: "将…存入银行；倾斜转弯", type: "v" },
    ],
    phrases: [
      { phrase: "central bank", translation: "[经]中央银行" },
      { phrase: "commercial bank", translation: "商业银行" },
      { phrase: "bank of china", translation: "中国银行" },
      { phrase: "world bank", translation: "n. 世界银行" },
      { phrase: "bank account", translation: "银行存款；银行往来帐户" },
      { phrase: "people's bank of china", translation: "中国人民银行" },
      { phrase: "investment bank", translation: "投资银行" },
      { phrase: "development bank", translation: "开发银行" },
      { phrase: "construction bank", translation: "建设银行" },
      { phrase: "west bank", translation: "约旦河西岸" },
      { phrase: "bank credit", translation: "银行信贷；银行信用状" },
      { phrase: "bank loan", translation: "银行贷款" },
      { phrase: "agricultural bank", translation: "农业银行" },
      { phrase: "industrial and commercial bank", translation: "工商银行" },
      { phrase: "issuing bank", translation: "开证银行；发行钞票的银行" },
      { phrase: "river bank", translation: "河岸；河堤" },
      { phrase: "china construction bank", translation: "中国建设银行" },
      { phrase: "in bank", translation: "存入银行" },
      { phrase: "bank on", translation: "指望；依赖" },
      { phrase: "bank of america", translation: "n. 美国银行" },
    ],
  },
  {
    word: "basic",
    translations: [
      { translation: "基本的；基础的", type: "adj" },
      { translation: "基础；要素", type: "n" },
    ],
    phrases: [
      { phrase: "basic principle", translation: "基本原理" },
      { phrase: "basic theory", translation: "基本理论" },
      { phrase: "basic level", translation: "基本水平" },
      { phrase: "basic knowledge", translation: "基础知识，基本知识" },
      { phrase: "basic concept", translation: "基本概念；本义" },
      { phrase: "basic structure", translation: "基本结构" },
      { phrase: "basic education", translation: "基础教育" },
      { phrase: "basic research", translation: "基本研究" },
      { phrase: "basic information", translation: "基本信息；基本资料" },
      { phrase: "basic data", translation: "基本资料；原始数据" },
      { phrase: "basic function", translation: "基本功能；基本函数" },
      {
        phrase: "basic law",
        translation: "基本法律；一国或一邦的政府的基本组织的书面说明",
      },
      { phrase: "basic unit", translation: "基本单元" },
      { phrase: "basic ideas", translation: "n. 基本观念" },
      { phrase: "basic course", translation: "基础课，基础课程；基本训练" },
      { phrase: "basic framework", translation: "基本框架" },
      { phrase: "basic design", translation: "基本设计；原图" },
      { phrase: "basic approach", translation: "基本方法" },
      { phrase: "basic english", translation: "基础英语" },
      { phrase: "basic model", translation: "基本模型" },
    ],
  },
  {
    word: "basket",
    translations: [
      { translation: "篮子；（篮球比赛的）得分；一篮之量；篮筐", type: "n" },
      { translation: "装入篮", type: "vt" },
    ],
    phrases: [
      { phrase: "picnic basket", translation: "野餐篮" },
      { phrase: "fruit basket", translation: "果篮，水果篮" },
      { phrase: "bamboo basket", translation: "竹篮；竹篓" },
      { phrase: "shopping basket", translation: "购物篮；提篮" },
      {
        phrase: "basket case",
        translation: "四肢不全的人；完全伤残者；完全没有希望的人",
      },
      { phrase: "hanging basket", translation: "挂篮；吊篮" },
      {
        phrase: "a basket of currencies",
        translation: "[经]笼统货币；一篮子货币",
      },
      { phrase: "laundry basket", translation: "洗衣篮" },
      { phrase: "wastepaper basket", translation: "废纸篓" },
      { phrase: "rattan basket", translation: "藤篮" },
      { phrase: "bread basket", translation: "产粮区；面包篮；谷物产品" },
    ],
  },
  {
    word: "basketball",
    translations: [{ translation: "篮球；篮球运动", type: "n" }],
    phrases: [
      { phrase: "play basketball", translation: "打篮球" },
      { phrase: "basketball player", translation: "n. 篮球选手；篮球球员" },
      { phrase: "basketball game", translation: "篮球比赛；篮球运动" },
      { phrase: "basketball court", translation: "篮球场" },
      {
        phrase: "national basketball association",
        translation: "国家篮球协会（简称NBA）",
      },
      { phrase: "basketball shoe", translation: "篮球鞋" },
      { phrase: "basketball field", translation: "篮球场" },
    ],
  },
  {
    word: "bathroom",
    translations: [{ translation: "浴室；厕所；盥洗室", type: "n" }],
    phrases: [
      { phrase: "bathroom accessories", translation: "浴室配件" },
      { phrase: "go to the bathroom", translation: "上厕所" },
      { phrase: "bathroom cabinet", translation: "浴室柜" },
      { phrase: "bathroom equipment", translation: "浴室设备" },
      { phrase: "bedroom and bathroom", translation: "卧室和浴室" },
      { phrase: "bathroom scale", translation: "浴室磅秤；体重秤" },
    ],
  },
  {
    word: "be",
    translations: [
      { translation: "是； 有，存在； 做，成为； 发生", type: "v" },
      {
        translation: "(Be)人名；(缅)拜；(日)部(姓)；(朝)培；(中非)贝",
        type: "n",
      },
    ],
    phrases: [
      { phrase: "so be it", translation: "诚心所愿；顺其自然" },
      { phrase: "let be", translation: "听任；不干涉，不打扰" },
    ],
  },
  {
    word: "beach",
    translations: [
      { translation: "海滩；湖滨", type: "n" },
      { translation: "将…拖上岸", type: "v" },
    ],
    phrases: [
      {
        phrase: "on the beach",
        translation: "adj. 在海滩上；失业的；潦倒的；退休的",
      },
      { phrase: "at the beach", translation: "在海边；在海滩上" },
      { phrase: "beach volleyball", translation: "沙滩排球，排球" },
      { phrase: "sandy beach", translation: "沙滩；砂质海滩" },
      { phrase: "go to the beach", translation: "去海滩；去海边；去沙滩" },
      { phrase: "sand beach", translation: "沙滩，沙质海滩" },
      {
        phrase: "long beach",
        translation: "长滩（美国加州西南部港市）；长滩（美国纽约州东南部城市）",
      },
      { phrase: "bathing beach", translation: "n. 海水浴场" },
      { phrase: "beach resort", translation: "海滩度假村" },
      {
        phrase: "beach umbrella",
        translation: "n. （美）遮阳伞（海滨或花园用的）",
      },
      {
        phrase: "palm beach",
        translation: "棕榈滩（位于美国佛罗里达州东南部）",
      },
      {
        phrase: "miami beach",
        translation: "迈阿密海滩（位于美国佛罗里达州）",
      },
      { phrase: "golden beach", translation: "金色的海滨" },
      { phrase: "sea beach", translation: "海滩；海滨" },
      { phrase: "beach house", translation: "n. 海滨别墅" },
      { phrase: "beach towel", translation: "沙滩毛巾；沙滩浴巾；海滩浴巾" },
      {
        phrase: "beach ball",
        translation: "（在海滨，游泳池等玩的）大充气球，水皮球",
      },
      { phrase: "beach party", translation: "海滩派对（等于shore party）" },
      {
        phrase: "virginia beach",
        translation: "维珍尼亚滩（美国弗吉尼亚州东南部城市）",
      },
      { phrase: "west palm beach", translation: "西棕榈滩（美国度假胜地）" },
    ],
  },
  {
    word: "bear",
    translations: [
      { translation: "结果实，开花（正式）", type: "v" },
      { translation: "熊", type: "n" },
    ],
    phrases: [
      { phrase: "bear oneself", translation: "举止，表现；为人处事" },
      { phrase: "bear in mind", translation: "vi. 记住；考虑到" },
      { phrase: "bear market", translation: "熊市；空头市场；卖空市场" },
      { phrase: "polar bear", translation: "北极熊" },
      { phrase: "teddy bear", translation: "泰迪熊" },
      {
        phrase: "bear on",
        translation: "对…施加压力；与…有关；对…有影响；瞄准",
      },
      { phrase: "bear with", translation: "忍受；宽容" },
      { phrase: "bear fruit", translation: "结出果实；奏效" },
      { phrase: "black bear", translation: "[动]（北美，亚洲）黑熊" },
      { phrase: "bear hardships", translation: "吃苦；吃苦耐劳" },
      { phrase: "bear the weight of", translation: "承载；支撑；承受…的重量" },
      { phrase: "bear the palm", translation: "获奖；获胜" },
      { phrase: "bear arms", translation: "携带武器；当兵" },
      { phrase: "bear stearns", translation: "贝尔斯登（美国投资银行）" },
      { phrase: "little bear", translation: "小熊座" },
      { phrase: "bear the brunt", translation: "首当其冲；承受打击" },
      { phrase: "big bear", translation: "大熊；大支承" },
      { phrase: "bring to bear", translation: "施加" },
      { phrase: "brown bear", translation: "棕熊，棕色熊" },
      { phrase: "bear the brunt of", translation: "首当其冲" },
    ],
  },
  {
    word: "beautiful",
    translations: [{ translation: "美丽的", type: "adj" }],
    phrases: [
      { phrase: "so beautiful", translation: "如此美丽；如此漂亮" },
      { phrase: "beautiful girl", translation: "美丽姑娘" },
      { phrase: "beautiful woman", translation: "美人；漂亮的女人" },
      { phrase: "how beautiful", translation: "如此美好；美极了" },
      { phrase: "beautiful view", translation: "美丽的景色，美丽景观" },
      { phrase: "life is beautiful", translation: "美丽人生（电影名称）" },
      { phrase: "beautiful people", translation: "美丽的人民，名流" },
      { phrase: "beautiful lady", translation: "美丽的女人" },
      { phrase: "beautiful eyes", translation: "美丽的眼睛" },
      { phrase: "beautiful design", translation: "造型优美" },
      { phrase: "beautiful morning", translation: "美丽的早晨" },
      { phrase: "beautiful work", translation: "完美的工作" },
      { phrase: "very beautiful flowers", translation: "姹紫嫣红" },
    ],
  },
  {
    word: "because",
    translations: [{ translation: "因为", type: "conj" }],
    phrases: [{ phrase: "because of", translation: "adv. 因为；由于" }],
  },
];
export default tryList;
